apiVersion: 1
datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus-kube-prometheus-prometheus.default.svc:9090
    isDefault: true
    jsonData:
      httpMethod: POST
